spring.application.name=auth-service

server.port=8080
logging.level.org.springframework.security=DEBUG

spring.security.oauth2.client.registration.keycloak.client-id=my-client
spring.security.oauth2.client.registration.keycloak.client-secret=SEU_SECRET
spring.security.oauth2.client.registration.keycloak.scope=openid

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/java-the-hutt