server:
  port: 8080

spring:
  application:
    name: servico-gateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddRequestHeader=X-Gateway, servico-gateway
          routes:
            - id: servico-gestao
              uri: http://localhost:8082
              predicates:
                - Path=/gestao/**
              filters:
                - StripPrefix=1
            - id: servico-apontamento
              uri: http://localhost:8083
              predicates:
                - Path=/apontamento/**
              filters:
                - StripPrefix=1
            - id: servico-auditoria
              uri: http://localhost:8084
              predicates:
                - Path=/auditoria/**
              filters:
                - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/java-the-hutt/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    io.netty: WARN
    reactor.netty: WARN
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG
