spring.application.name=app
server.port=8086

# mysql
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/app?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:apppass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# SEGURANCA (OAuth2 Resource Server)
# Se estiver a usar um Identity Provider (ex: Keycloak ou Auth0), indique a URI do emissor:
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://seu-auth-server.com/realms/meu-realm
# para rodar localmente:
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/realms/java-the-hutt}

# Ou, se tiver a chave publica localmente:
# spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:public.key

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:rabbit}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:rabbit}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VIRTUAL_HOST:/}

# Actuator
# Expor todos os endpoints
# management.endpoints.web.exposure.include=*
# management.endpoint.health.show-details=always



#spring.application.name=App
#
## ======================
## MariaDB (ATIVO)
## ======================
#spring.datasource.url=jdbc:mariadb://localhost:3306/gsw_api?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=fatec
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## ======================
## MySQL (DESATIVADO)
## ======================
## spring.datasource.url=jdbc:mysql://localhost:3306/gsw_api?createDatabaseIfNotExist=true
## spring.datasource.username=root
## spring.datasource.password=12345678
## spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## ======================
## JPA / Hibernate
## ======================
# spring.jpa.hibernate.ddl-auto=update
spring.session.jdbc.initialize-schema=always